# Generated by Django 3.2.5 on 2021-07-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210730_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
